### ISSUE TITLE
Updating items throws mysql error

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-OmekaApiImport#10]
```
Zend_Db_Statement_Mysqli_Exception: Mysqli statement execute error : Column 'html' cannot be null in /var/www/html/omeka2/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/html/omeka2/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/html/omeka2/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/html/omeka2/application/libraries/Omeka/Db.php(79): Zend_Db_Adapter_Abstract->query('INSERT INTO `om...', Array)
#3 /var/www/html/omeka2/application/libraries/Omeka/Db.php(255): Omeka_Db->__call('query', Array)
#4 /var/www/html/omeka2/application/libraries/Omeka/Record/AbstractRecord.php(541): Omeka_Db->insert('omeka_element_t...', Array)
#5 /var/www/html/omeka2/application/models/Builder/Item.php(113): Omeka_Record_AbstractRecord->save()
#6 /var/www/html/omeka2/application/models/Builder/Item.php(245): Builder_Item->_replaceElementTexts()
#7 /var/www/html/omeka2/application/libraries/Omeka/Record/Builder/AbstractBuilder.php(66): Builder_Item->_beforeBuild(Object(Item))
#8 /var/www/html/omeka2/application/libraries/globals.php(589): Omeka_Record_Builder_AbstractBuilder->build()
#9 /var/www/html/omeka2/plugins/OmekaApiImport/libraries/ApiImport/ResponseAdapter/Omeka/ItemAdapter.php(16): update_item(Object(Item), Array, Array)
#10 /var/www/html/omeka2/plugins/OmekaApiImport/libraries/ApiImport/ImportJob/Omeka.php(94): ApiImport_ResponseAdapter_Omeka_ItemAdapter->import()
#11 /var/www/html/omeka2/plugins/OmekaApiImport/libraries/ApiImport/ImportJob/Omeka.php(32): ApiImport_ImportJob_Omeka->importRecords('items', Object(ApiImport_ResponseAdapter_Omeka_ItemAdapter))
#12 /var/www/html/omeka2/application/libraries/Omeka/Job/Process/Wrapper.php(29): ApiImport_ImportJob_Omeka->perform()
#13 /var/www/html/omeka2/application/scripts/background.php(61): Omeka_Job_Process_Wrapper->run(Array)
#14 {main}
```

**Comment by patrickmj** [comment]
This is an artifact of having filtering turned on for the source site's API. It strips out the HTML flag, which is as it should be.
